main: com.xgolden.tabcompleter.Main
name: CustomTabCompleter
version: '1.2.1'
author: xGolden_
commands:
   tabcompleter:
      description: CustomTabCompleter's main command.
      usage: /<command>
      aliases: [ctc, tc, tabc, tcompleter]