main: com.xgolden.tabcompleter.Main
name: CustomTabCompleter
version: '1.0.3.1'
author: xGolden_
commands:
   tabcompleter:
      description: CustomTabCompleter's main command.
      usage: /<command>
      aliases: [tc, tabc, tcompleter]